### ISSUE TITLE
Skypilot S3 file_mounts is Hardcoded

### ISSUE THREAD

**Issue by caseyoneill** [Trainy-ai/llm-atc#5]
I was attempting to follow the [instructions](https://trainy.ai/blog/chat_complete) provided for replacing the OpenAI API using llm-atc and I received the following error message when running the serve command that is provided in the 
documentation:

```
I 09-15 11:11:41 optimizer.py:821] 
E 09-15 11:11:41 storage.py:762] Could not get StoreType.S3 store with name llm-atc.
botocore.exceptions.ClientError: An error occurred (403) when calling the HeadBucket operation: Forbidden

The above exception was the direct cause of the following exception:

sky.exceptions.StorageBucketGetError: Failed to access existing bucket 'llm-atc'. This is likely because it is a private bucket you do not have access to.
To fix: 
  1. If you are trying to create a new bucket: use a different name.
  2. If you are trying to connect to an existing bucket: make sure your cloud credentials have access to it. To debug, consider running `aws s3 ls llm-atc`.
```
Is this because the s3 bucket `llm-atc` is hardcoded in the serve.yml [file_mounts property](https://github.com/Trainy-ai/llm-atc/blob/bc2d1d053d58f30f97ec9f2c3e1d0c02901612d4/llm_atc/config/serve/serve.yml#L8)? Should this be a command line parameter?

**Comment by asaiacai** [comment]
Discussed offline with @caseyoneill, yes the object store is hardcoded. This will fail if the object store hasn't already been created and seems to be causing issues with other users who don't have the s3 bucket creation permissions. Going to refactor so that if users just want to serve a non-llm atc model to skip mounting s3
